INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'MERN',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'ANGULAR',TRUE, '2022-05-31', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (2,'ANGULAR',TRUE, '2022-05-31', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'REACT',TRUE, '2022-05-31', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'RNR',TRUE, '2022-05-31', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'RUBY',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,TRUE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'REACT',TRUE, '2022-05-31', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'MERN',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'MERN',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'MERN',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'MERN',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'MERN',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (2,'MERN',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'MERN',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'MERN',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'MERN',FALSE, '2022-05-31', FALSE, TRUE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'MERN',FALSE, '2022-05-31', FALSE, TRUE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'MERN',FALSE, '2022-05-31', FALSE, TRUE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'MERN',FALSE, '2022-05-31', FALSE, FALSE, TRUE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'MERN',FALSE, '2022-05-31', FALSE, FALSE, TRUE,FALSE,FALSE,TRUE,FALSE);


