INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'MERN',TRUE, '2022-05-31', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'ANGULAR',TRUE, '2022-06-03', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (2,'ANGULAR',TRUE, '2022-06-05', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'REACT',TRUE, '2022-06-13', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'RNR',TRUE, '2022-06-14', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'RUBY',TRUE, '2022-06-30', FALSE, FALSE, FALSE,FALSE,TRUE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'REACT',TRUE, '2022-05-22', FALSE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'MERN',TRUE, '2022-05-27', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'PERN',TRUE, '2022-07-01', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'PHP',TRUE, '2022-06-30', FALSE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'#NET',FALSE, '2022-05-31', TRUE, FALSE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'REACT',FALSE, '2022-05-05', TRUE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (2,'Vanilla JS',FALSE, '2022-01-07', TRUE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'RUBY',FALSE, '2022-06-13', TRUE, FALSE, FALSE,FALSE,TRUE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (6,'JQUERY',FALSE, '2022-03-21', TRUE, FALSE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'PERN',FALSE, '2022-07-28', FALSE, TRUE, FALSE,FALSE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (4,'JQUERY',FALSE, '2022-07-22', FALSE, TRUE, FALSE,TRUE,FALSE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (5,'MERN',FALSE, '2022-08-14', FALSE, TRUE, FALSE,FALSE,FALSE,TRUE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (3,'NODE.JS',FALSE, '2022-11-30', FALSE, FALSE, TRUE,FALSE,TRUE,FALSE,FALSE);
INSERT INTO applications(company_id,stack,resume_sent,resume_sent_date,hr_interview,tech_interview,job_offer,front_end,back_end,full_stack,rejected) VALUES (1,'PERN',FALSE, '2022-12-31', FALSE, FALSE, TRUE,FALSE,FALSE,TRUE,FALSE);


